### ISSUE TITLE
File "train.py", line 739, in main     class_count = len(image_lists.keys()) AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by monajalal** [loicmarie/sign-language-alphabet-recognizer#8]
Hey how do you actually run this?
What are the step-by-step commands to get this going?

```
[jalal@goku sign-language-alphabet-recognizer]$ python train.py 
/scratch/sjn/anaconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
Image directory '' not found.
Traceback (most recent call last):
  File "train.py", line 1022, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 739, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

```

**Comment by mishra-tanay** [comment]
I think you are not working on a opencv environment  .
Check if you have installed python dependencies using pip install. 
then try running by 
' python3 train.py dataset

**Comment by teodorabotez** [comment]
I'm using conda so i tried to train and this showed:


Traceback (most recent call last):
  File "train.py", line 1022, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
AttributeError: module 'tensorflow' has no attribute 'app'

**Comment by csyjin6** [comment]
any update for this thread?

**Comment by samik-rathore** [comment]
can someone solve the issue?

**Comment by ghost** [comment]
> I'm using conda so i tried to train and this showed:
> 
> Traceback (most recent call last): File "train.py", line 1022, in tf.app.run(main=main, argv=[sys.argv[0]] + unparsed) AttributeError: module 'tensorflow' has no attribute 'app'

replace all tf. with tf.compat.v1.
